name: 'Setup eBPF build dependencies'
description: 'Install Rust nightly + rust-src required to compile huginn-proxy-ebpf-xdp for bpfel-unknown-none'
runs:
  using: 'composite'
  steps:
    - name: Install Rust nightly with rust-src
      shell: bash
      run: rustup toolchain install nightly --component rust-src
    - name: Install bpf-linker
      shell: bash
      # Use nightly to compile bpf-linker: its deps require rustc > the stable MSRV in this repo.
      # --locked pins to the exact dep versions in bpf-linker's published Cargo.lock.
      run: cargo +nightly install bpf-linker --locked
