[package]
name = "huginn-proxy"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[features]
ebpf-tcp = ["dep:huginn-ebpf"]

[dependencies]
arc-swap.workspace = true
clap.workspace = true
huginn-ebpf = { workspace = true, optional = true }
huginn-proxy-lib.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
tracing.workspace = true

[dev-dependencies]
serde_json.workspace = true
