[package]
name = "huginn-ebpf"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
build = "src/build.rs"

[dependencies]
aya.workspace = true
aya-log.workspace = true
getrandom.workspace = true
huginn-ebpf-common = { workspace = true, features = ["aya"] }
huginn-ebpf-rate-limit.workspace = true
huginn-net-tcp.workspace = true
log.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
huginn-ebpf-common = { workspace = true }
libc.workspace = true
