name: 'Setup Chrome and chromedriver'
description: 'Install Chrome browser, chromedriver, and start chromedriver service'
inputs:
  chromedriver-port:
    description: 'Port for chromedriver'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Chrome
      uses: browser-actions/setup-chrome@v2
      with:
        chrome-version: latest
    
    - name: Install chromedriver
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
        chromedriver --version
    
    - name: Start chromedriver
      shell: bash
      run: |
        pkill -f chromedriver || true
        sleep 1
        chromedriver --port=${{ inputs.chromedriver-port }} --log-path=/tmp/chromedriver.log &
        sleep 3
        for i in {1..10}; do
          if curl -s http://localhost:${{ inputs.chromedriver-port }}/status > /dev/null 2>&1; then
            echo "chromedriver is running"
            break
          fi
          echo "Waiting for chromedriver... ($i/10)"
          sleep 1
        done
        curl -s http://localhost:${{ inputs.chromedriver-port }}/status || (cat /tmp/chromedriver.log && exit 1)