services:
  proxy:
    build:
      context: ..
      dockerfile: docker/proxy.Dockerfile
      target: plain
    command: ["/usr/local/bin/huginn-proxy"]
    environment:
    # - HUGINN_CONFIG_PATH=/config/compose.toml
      - HUGINN_CONFIG_PATH=/config/compose.yaml
      - HUGINN_WATCH=true
      - HUGINN_WATCH_DELAY_SECS=60
    volumes:
      #- ./config/compose.toml:/config/compose.toml:ro
      - ./config/compose.yaml:/config/compose.yaml:ro
      - ./certs:/config/certs:ro
    ports:
      - "0.0.0.0:7000:7000"   # Proxy server IPv4
      - "[::]:7000:7000"       # Proxy server IPv6
      - "0.0.0.0:9090:9090"   # Observability server IPv4 (Metrics + Health checks)
      - "[::]:9090:9090"       # Observability server IPv6
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1:9090/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 10s
    depends_on:
      backend-a:
        condition: service_started
      backend-b:
        condition: service_started

  backend-a:
    build:
      context: ..
      dockerfile: examples/backend/Dockerfile

  backend-b:
    build:
      context: ..
      dockerfile: examples/backend/Dockerfile

networks:
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.28.0.0/16
        - subnet: fd00:dead:beef:1::/64
