name: 'Setup Firefox and geckodriver'
description: 'Install Firefox browser and geckodriver for browser testing'
inputs:
  firefox-version:
    description: 'Firefox version to install (e.g., "147.0")'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Firefox
      uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: ${{ inputs.firefox-version }}
    
    - name: Install geckodriver
      shell: bash
      run: |
        GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r '.tag_name')
        wget https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VERSION}/geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz
        tar -xzf geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin/
        geckodriver --version
