name: 'Setup Firefox and geckodriver'
description: 'Install Firefox browser, geckodriver, and start geckodriver service'
inputs:
  firefox-version:
    description: 'Firefox version to install (e.g., "147.0")'
    required: true
  geckodriver-port:
    description: 'Port for geckodriver'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Firefox
      uses: browser-actions/setup-firefox@v1
      with:
        firefox-version: ${{ inputs.firefox-version }}
    
    - name: Install geckodriver
      shell: bash
      run: |
        GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r '.tag_name')
        wget https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VERSION}/geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz
        tar -xzf geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin/
        geckodriver --version
    
    - name: Start geckodriver
      shell: bash
      run: |
        pkill -f geckodriver || true
        sleep 1
        geckodriver --port ${{ inputs.geckodriver-port }} --log trace &
        sleep 3
        for i in {1..10}; do
          if curl -s http://localhost:${{ inputs.geckodriver-port }}/status > /dev/null 2>&1; then
            echo "geckodriver is running"
            break
          fi
          echo "Waiting for geckodriver... ($i/10)"
          sleep 1
        done
        curl -s http://localhost:${{ inputs.geckodriver-port }}/status || (echo "geckodriver failed to start" && exit 1)
