[package]
name = "tests-e2e"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
huginn-proxy-lib.workspace = true
reqwest.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "net"] }

[dev-dependencies]
serial_test.workspace = true

[[test]]
name = "e2e"
path = "tests/e2e.rs"

