[package]
name = "tests-browsers"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
name = "tests_browsers"
path = "src/lib.rs"

[dependencies]
huginn-proxy-lib.workspace = true
serial_test.workspace = true
thirtyfour = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[[test]]
name = "chrome"
path = "tests/chrome.rs"

[[test]]
name = "firefox"
path = "tests/firefox.rs"
